### ISSUE TITLE
Add Doxygen docs to gh-pages

### ISSUE THREAD

**Issue by AE9RB** [thingSoC/embedis#11]
Here's a guide:
http://rickfoosusa.blogspot.com/2011/10/howto-use-doxygen-with-github.html

Make sure the link in the readme works after.

Also, check in an empty .nojekyll file to root of gh-pages branch. This isn't covered in the above guide but I found it to be necessary.

**Comment by moxondesign** [comment]
Done, but a separate branch - not a nested repo...

**Comment by AE9RB** [comment]
515d6c033f713fcbc5d8cebd06d5d0ae993c66a8
