### ISSUE TITLE
Can we use SPIFFS instead of EEPROM in ESP8266 ? 

### ISSUE THREAD

**Issue by arihantdaga** [thingSoC/embedis#16]
ESP8266 has an issue about EEPROM- That is it have limited write cycles(Approx 10000) after that Flash(Which is actually used for emulating EEPROM in ESP8266) Starts wearing. I have faced this, using embedis- after multiple writes Sometimes embedis dictionary is starting empty(Data got cleared). So people suggested we can use SPIFFS instead of EEPROM for better reliability. 
Can this library support writing to spiffs ?

**Comment by moxondesign** [comment]
Hi,
Yes, you are absolutely correct, in that EEPROM emulation in the ESP8266 uses the main FLASH memory, as there is no physical EEPROM on most ESP8266 boards. However, the SPIFFS acronym stands for "SPI FLASH File System" so it has the exact same issues (it is merely an API change). 
There are two options if you need to do a lot of write cycles.
The first is to create a RAM based dictionary for heavy write-cycle usage, 
and save/restore that RAM dictionary to FLASH during power down/power up.
Second choice is to add a real EEPROM(or NVSRAM, FRAM, etc.) to your design.
I have posted an example of that here 
https://hackaday.io/project/19446-embedis-i2c-fram-keystore

The idea of using the "Emulated EEPROM" on the ESP8266 is for low-write-cycle,
high-read-cycle usage, such as storing settings that don't change frequently.
For other usage models, I suggest using an actual EEPROM or FRAM/NVSRAM.
